# Generated by Django 4.2.7 on 2023-11-15 17:00

import apps.account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=220)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('activation_code', models.CharField(blank=True, max_length=255)),
                ('activation_phone_code', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=False)),
                ('is_phone_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', apps.account.models.UserManager()),
            ],
        ),
    ]
