# Generated by Django 4.2.7 on 2023-11-16 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimages',
            old_name='post',
            new_name='car',
        ),
    ]
